main/static/main/css/style.css
main/static/main/js/geo.js
main/static/main/js/map.js
main/static/main/js/review.js
main/templates/main/map.html
main/templates/main/review.html
main/templatetags/__init__.py
main/templatetags/representable_extras.py
main/views.py

- hover over communities
- view by name/reason
- removed issues/tags aspects
- census blocks shading by population on entry page
- removed zip code modal on map page

map + review page updates

---

representable/settings/prod.py

changed DEBUG to False for prod

---

representable/settings/base.py
representable/settings/dev.py
representable/settings/prod.py

Resolves #100 
- Moves email verification code out of base.py and into prod.py

Move email verification settings to settings/prod.py

---

main/views/main.py

fixes #71 
Delete should work as expected now. To test, create a new entry and delete it. The form should delete it in one click.

fixed faulty 'delete' button form

---

main/templates/main/campaigns/page.html
main/templates/main/dashboard/campaigns/index.html
main/templates/main/partners/map.html
main/urls.py
main/views/dashboard.py
main/views/partners.py

**Main changes:**
- Adds url for campaign map (parameter to existing org map)
- Adds url for campaign review (parameter to existing org review)
- Campaign dashboard home updated
**Key steps to replicate:**
- Create campaign
- Go to review page
- Check out links to campaign page, review page, and map
- Create a submission with this campaign
- See that campaign map now updated with your community
**Screenshots:**

Campaign map/review page

---

main/static/main/css/style.css
main/templates/main/pages/entry.html

Resolves #113 
To replicate:
1. Go to home page. Check the CSS and console. Click some states to make sure they redirect to the right page.
2. Go to entry page. Read text in Personal Info alert. It should now make sense.

Fixing Front Page CSS Problems + Hotfix for entry page

---

main/forms.py
main/templates/main/pages/entry.html
main/views/main.py

- Added phone number validation
- clean function added in the backend for the phone number field
- alert added on the form

Entry Page - Phone number validation - frontend and backend

---

main/templates/main/base.html

Closes #124. Fixes privacy/terms links in the footer on base template.

Fix Privacy/Terms Links in footer

---

main/forms.py
main/static/main/css/style.css
main/templates/main/pages/entry.html

Closes #120.
- Adds a checkbox for TOC/Privacy at the end of the form.
- Changes color of "What comes next?" from yellow (warning) to blue (info).

Adds TOC/Privacy Checkbox at the end of the form.

---

main/static/main/js/map.js
main/templates/main/dashboard/partners/review.html
main/templates/main/pages/map.html
main/templates/main/pages/review.html
main/templates/main/pages/submission.html
main/templates/main/partners/map.html
main/templatetags/representable_extras.py
main/views/dashboard.py
main/views/main.py
main/views/partners.py

- Visualizations now include the other issues field, addresses (for those with permission to see them), and have been cleaned up a bit to look nicer
** to see **
go to any map page yee haw 🤠

visualizations fully updated

---

main/forms.py
main/templates/main/pages/entry.html

- changed widget to textinput to add placeholder
- django-phone-field didn't take in args for placeholder

Phone number field

---

main/static/main/js/geo.js
main/templates/main/pages/entry.html

- added steps to explain the controls on the map
- added button that would trigger the tour
- button only shows once the map is revealed

Added shepherd.js for map drawing

---

main/templates/main/pages/about.html

Key changes:
- Make paragraph larger and more legible
- Create spacing between cards and footer
Steps to test:
- Visit about page

Minor about page fixes

---

main/templates/main/campaigns/page.html

Key changes:
- Makes headings bold per @psiyer7 suggestions
To replicate:
- visit a campaign page
Screenshots:

Minor campaign page fix

---

main/templates/main/pages/entry.html

* Removed organization field from Entry Page

Removed Organization Field from Entry Page

---

main/templates/main/pages/entry.html

- old link to user guide added in the help dropup

added link to old user guide

---

main/forms.py

removed example placeholder in the interests field on the entry page

---

main/templates/main/pages/entry.html

fix rounded corners

---

main/templates/main/dashboard/partners/membership.html
main/views/dashboard.py

Key Changes:
Solves issue https://github.com/Representable/securetracker/issues/4.
To replicate: 
Visit org-membership page dashboard -> org -> membership -> see table.

Member form display issue

---

main/templates/main/pages/entry.html

click on the user guide in the help dropup on the entry page, and another tab should open

open up link in new tab

---

main/forms.py
main/static/main/js/geo.js
main/templates/main/pages/entry.html
main/templates/main/pages/thanks.html

Updated changes based on conversations with our partners.
1. **Entry page** is updated per our internal conversation.
a. Added instructions to get started.
b. Changed "Personal Information" to "Identifying Information"
c. Clarified instructions for filing interests fields.
d. Removed "Recommended" tags.
e. Changed the order of interests fields.
d. Removed issues (front-end ONLY for now). Discuss during meeting.
e. Updated instructions for drawing community.
f. Changed "vertex" to "point" on front-end.
g. Added disclaimer about editing communities on entry page.
h. Renamed "Save Entry" to "Save Community".
2. Updated **Thanks Page**.
a. Added updated disclaimer.
b. Added "Send Feedback" button and section.
Screenshots:

Content Changes

---

main/static/main/css/style.css
main/static/main/js/geo.js
main/templates/main/pages/entry.html

Resolves #172 and minor changes.
Fixes the Safari Compatibility bug.
1. Adds numbering to Privacy and terms.
2. Fixes spacing for the geocoder.

Fix Safari Bug

---

main/static/main/css/style.css
main/static/main/js/geo.js
main/templates/main/pages/entry.html

Updated vertex color to dark blue and orange.

Updated vertex colors.

---

main/static/main/js/geo.js
main/templates/main/index.html
main/templates/main/pages/entry.html

Removed mentions of vertices and polygons in the tutorial. Check the tutorial to check it out.
Also fixed a bug that prevented the tutorial from advancing.

Tutorial Update

---

main/templates/main/base.html

Updated navbar + footer links.
Removed Spanish translations from footer and navbar.

Updated Navbar + Footer Links

---

.gitignore
main/context_processors/mixpanel.py
main/models.py
main/static/main/js/geo.js
main/static/main/js/mixpanel.js
main/templates/account/email_confirm.html
main/templates/account/login.html
main/templates/account/logout.html
main/templates/account/signup.html
main/templates/account/verification_sent.html
main/templates/main/base.html
main/templates/main/campaigns/page.html
main/templates/main/index.html
main/templates/main/pages/entry.html
main/templates/main/pages/michigan.html
main/templates/main/pages/thanks.html
main/views/campaigns.py
main/views/main.py
representable/settings/base.py

Added Mixpanel Analytics. 
For Reviewer:
1. Contact me about Mixpanel login details.
2. Go on Entry/Home/Account Creation pages and check the live feed in Mixpanel.
3. Log In/Log Out/Create Account to further see analytics working.
Check console for any latent errors.

Mixpanel Analytics

---

main/views/dashboard.py

resolves #215 .
Key changes:
- Clean up whitelist code, add emails one by one instead of using bulk_create function.
To test:
- Upload email whitelist
- Verify in postico that the right emails are added

Fix whitelist bulk create code

---

docs/README.md
docs/docs/doc2.md
docs/docs/docasaurus1.md
docs/docs/docasaurus2.md
docs/docusaurus.config.js
main/views/main.py

Removes references to is_member function, changes to is_org_admin

Fix is_member

---

main/views/main.py

Removes reference to is_member, changes to is_org_admin.

Change is_member to is_org_admin

---

main/templates/main/partners/map.html
main/urls.py
main/views/main.py
main/views/partners.py

**Changes:**
- moves geojson logic in views/main.py from ExportView to its own function
- creates MultiExportView in views/partners.py to export a geojson file that is a FeatureCollection of all the communities (which are FeatureCollections themselves)
- creates URLs to MultiExportView - one for organization map with drive, one for organization map without drive
- adds appropriate link to the partner map context
- adds button to partner map page to export geojson
**To test:**
- run server
- go to an organization map page and click "Export geoJSON"
- go to a drive map page and click "Export geoJSON"
Closes #230

Multiple community geojson

---

main/static/main/js/geo.js

Key changes: 
-Instead of auto toggling draw/erase on every click, this PR only toggles if a new button is selected
To test:
- Visit entry page
- Inspect js for errors

Simplify toggle behavior 

---

main/static/main/css/style.css
main/static/main/js/geo.js
main/templates/main/entry.html
main/templates/main/submission.html

closes #334 
**changes**
- restricts zoom out, zoom in
- adds red border to warning box for contiguity check on map
- bugfixes for edge cases when submitting empty community
**to test**
- zoom in and out
- try to select separate regions, check visualization
- try to submit empty community, check error
**screenshot**
(this is the minimum zoom level currently set)

small cosmetic changes to entry page map

---

main/static/main/js/geo.js

**Changes**
Bug: When navigating to an initial state all the units of that state are selected
Fixed the bug (clears selectbBox)
**To Replicate**
Navigate to an entry page associated with a state
Check to see that the units are not all initially selected
Play around with the select tool to see that things work as usual;.

resolving initial state map merge conflict

---

main/static/main/js/geo.js

**changes**
- added stop to tour on entry page with undo button
- tweaked a couple parts of step by step guide slightly
**to test**
- click on "step-by-step guide"
- confirm no unexpected behavior

add undo button to step by step guide

---

representable/settings/prod.py

Key changes:
- Add xss and nosniff settings
To test:
- Try submitting an entry and see if there are any issues with mapbox, etc. loading

Add xss and nosniff settings

---

main/templates/main/entry.html

Key changes:
- Updates the video tutorial link with a link to the new video by @okusio with the updated select tool
To test:
- Visit entry page and see that vid link is updated
Screenshot:

Update video link for new select tool

---

main/templates/main/dashboard/drives/index.html
main/templates/main/index.html

Resolves #365 
Key changes:
Fixes a bug where state code was appended to drive url in the dashboard
To test:
Visit link on dashboard

Fix link to drive on organization dashboard

---

main/static/main/js/main.js

**Change:**
- click on state on home page takes you to the state page for that state (the state page URL already handles redirects if the state object doesn't exist yet for that state)

fix the redirect when you click on a state on the home page

---

representable/settings/base.py
representable/settings/prod.py

Key changes:
- Move cookie, xframe settings from base.py to prod.py
To test:
- verify that logging in locally works
- also try merging into staging to make sure it works in the production env

Move cookie, xframe settings to prod.py

---

representable/<representable>locale/es/LC_MESSAGES/django.po

compared Google Doc with .po file and updated translations. E-mailed @lauren-johnston and @ETedward with questions regarding other translations on the .po file
Looks like a lot of index was filled in but I went in and compared the two. I'm happy to go in and keep translating anything with `msgstr` 😄 Have a great weekend!

Added in Spanish translations for index and entry

---

main/static/main/js/map.js
main/templates/main/partners/map.html

Closes #132 
**changes**
- adds a basic search bar to partner map pages, which filters entries based upon query
**to test**
- go to map page
- ensure search works as expected, with no js errors
**other considerations**
- will want to prioritize effective design of the visualization pages this fall

search for communities on map page

---

main/static/main/js/components/keys.js

as per feedback from CA, removed the neighborhoods data layer for being confusing/incomplete
**to test**
- go to organization map / submission page
- check no neighborhoods data layer

remove neighborhoods data layer

---

main/static/main/js/map.js
main/static/main/js/submission.js

Closes #391 
**changes**
- data layers moved beneath existing map layers, as per bug report 391
**to test**
- go to map page or submission page, check lines are visible above map layers
(to determine in the future -- do we want these lines thicker? we had them that way before, but if i'm being honest, it was really ugly)
**screenshot**

moved data layers beneath existing map layers

---

main/forms.py
main/static/main/css/style.css
main/static/main/js/geo.js
main/templates/main/dashboard/index.html
main/templates/main/entry.html
main/templates/main/index.html
main/templates/main/map.html
main/templates/main/pages/about.html
main/templates/main/pages/blog.html
main/templates/main/partners/get_started.html
main/templates/main/partners/index.html
main/templates/main/partners/map.html
main/templates/main/state.html
representable/templates/base.html

**changes**
- added html alt-text, aria-labelledby, role, etc for accessibility
- added labels to form fields
- updated translation button in footer to fit in better

various accessibility updates

---

main/views/partners.py

@arorasomya this can be test 1 out of the tests I'm making, run it with the same tests as you ran for the db, and when you send me the locust reports you can call that one "db plain", and this one "test 1"? 
anyway, this is just putting a "defer" command so that django doesn't load those fields, on just the partner map query, for testing purposes

Exclude_all_geo (to merge with staging when we're ready for next tests)

---

main/views/main.py
main/views/partners.py

crudely removes processing from views our testing reaches
@arorasomya we have test 3!

no processing test 3

---

main/db_replacement.py
main/views/main.py
main/views/partners.py

for testing! it looks like it isn't working but dw this should be doing the right thing!

make the changes

---

main/views/partners.py

Performance

---

main/views/main.py
main/views/partners.py

added entry timestamp

---

representable/settings/base.py

update conn max age setting

---

main/templates/main/partners/map.html
main/views/partners.py

hacky way to test speed of sql

---

main/templates/main/partners/map.html
main/views/partners.py

Reverts Representable/representable#468

Revert "hacky way to test speed of sql" to get to a stage to test db conn

---

representable/settings/base.py

changed db conn to 300

---

representable/settings/base.py

changed db conn to 60 (a minute)

---

main/urls.py

fixed michaels's url bug for state submission

---

main/static/main/css/style.css
main/templates/account/signup_login.html

Fixes styling on input boxes in the auth pages.

Auth input fix

---

main/static/main/js/geo.js

flagged errors if address is required but not included
**to test**
- go to survey page
- try to submit community without address
- check that it doesn't allow you to submit

Fix form validation bug

---

main/views/main.py

For Testing Purposes
(Emailing PDF attachments)

email map setup

---

main/templates/main/entry.html

based on [this doc](https://www.notion.so/Survey-Questions-0c4a8b1318114496a659e90bbc56317b), updated the entry page questions, for use in user testing and for evaluation

Update entry page questions

---

main/views/partners.py

Need the requests to be made in parallel

Made the aws calls async

---

main/static/main/js/components/keys.js
main/static/main/js/map.js
main/static/main/js/submission.js

closes #267 
**changes**
- added a new data layer - US School districts
**to test**
- go to map page/submission page
- under "data layers" check and uncheck the school districts layer
- check no errors
**todo**
- add support for hovering and seeing names of school district layers

Add School Districts Data Layer

---

main/views/main.py

Changes:
- make map page use the optimized query (/map)
- use hardcoded id to get org with id 0 (on representable-dev that's vnp) so that query is for one org
To test:
- have an org with id 0 in the db and have non-aws community entries associated with that org
- run server and go to /map
- if this is a problem locally it should work really easily on staging and only affects /map and not the other maps

make map page fetch org 0 with opt

---

main/static/main/js/map.js
main/templates/main/partners/map.html
main/views/main.py

optimize client side map rendering by using only 1 layer
only tested for /map/p/ (both partner drive / map)

Map frontend optimize

---

main/static/main/js/map.js
main/templates/main/partners/map.html

Reverts Representable/representable#536

Revert "Map frontend optimize"

---

main/static/main/js/submission.js
main/templates/main/submission.html
main/views/main.py
representable/settings/dev.py
representable/urls.py

**Description**
After a user submits a map they will be greeted with a Thank You page with multiple options (including view community and send feedback). An additional option is send email is present; where when a user clicks the button, a pdf of the map will be generated and sent to the user's inbox. 
**Changes**
Email sending changes are done in submissions.html; submissions.js and enabled in main.py and urls.py. 
In addition to sending an email with a pdf, the bootstrap margins of the thank you box are reformatted to allow for more space. The following screenshots show the changes.
**Example Images**
Margins Before (for user w community drive) Looks very squished!
Thank You Box After Changes (for user w/ community drive) ...
Thank You Box After Changes (for user with community drive) …

Emailing PDF and Thank You Page

---

main/templates/main/map.html
main/urls.py
main/views/main.py

Go to a state map page:
/map/<abbreviation>
click on the two geojson export and csv export buttons

multi export working for state map pages

---

main/templates/main/entry_survey.html

changed wording to entry page to match designs
before survey
survey questions
mapping

update wording on entry pages

---

main/templates/main/submission.html

Adds a name card for the community name and the drive name to the submission page
*Mobile*
*iPad*
*iPad Pro*
*Laptop*

Submission Page Update

---

main/templates/main/submission.html

Adjusts the spacing between the filter buttons on the submission page.

Filter button spacing fix

---

main/templates/main/submission.html

Fixes the spacing between the cards and the buttons when a card is opened.

Add on buttons spacing fix

---

main/static/main/css/style.css
main/static/main/js/geo.js
main/templates/main/entry.html

**changes**
Adds a progressbar as shown in the figma mockup. Slight tweak to the design for the mobile view for now due to mobile compatibility reasons. A fix to make it look like as shown on the mockup may be in the works if necessary.
*Laptop*
*iPad Pro*
*iPad*
*Mobile*

Progress Bar Addition

---

main/static/main/css/style.css
main/templates/main/entry_address.html
main/templates/main/entry_map.html
main/templates/main/entry_privacy.html
main/templates/main/entry_survey.html
main/views/main.py

- Capitalizes the texts of the buttons in the entry page
- Adds the state definition to the entry survey page.

Capitalize buttons. Add state COI Def

---

main/static/main/js/geo.js
main/static/main/js/map.js
main/templates/main/entry_address.html
main/templates/main/entry_privacy.html
main/templates/main/entry_survey.html

**changes**
- fixes console error on survey page: "An invalid form control with name='' is not focusable."
- removes some print statements
**to test**
- go thru entry page survey
- check error above is not visible ^^

fix focus console errors

---

main/static/main/css/style.css
main/static/main/js/geo.js
main/static/main/js/map.js
main/templates/main/dashboard/partners/review.html
main/templates/main/entry_address.html
main/templates/main/entry_map.html
main/templates/main/entry_privacy.html
main/templates/main/entry_survey.html
main/templates/main/map.html
main/templates/main/partners/map.html
main/templates/main/review.html
main/templates/main/submission-copy.html
main/templates/main/submission.html

start of merging main into staging

Bugfix release - staging 01/18/2021

---

main/static/main/css/style.css
main/static/main/js/map.js
main/templates/main/map.html

fixes #579 
to test: go to any map page, and click on the dropdowns...the little arrows should be responsive and flip as needed.

Responsive arrows map page

---

main/templates/main/entry_survey.html

Staging release 02/27/2021

---

main/templates/main/entry_survey.html

Production release 02/27/2021

---

main/forms.py
main/static/main/css/style.css
main/static/main/js/geo.js
main/templates/main/entry_preview.html
main/templates/main/entry_survey.html
main/templates/main/index.html
main/templates/main/state.html

**changes**
- polishing fixes from the Kai polishing session

Polishing Fixes

---

main/static/main/js/components/keys.js
main/static/main/js/geo.js
main/urls.py
main/views/main.py
representable/templates/base.html

as per title, removes blog + link on navbar, adds 2020 block groups for AZ (per partner feedback), lowered warning message delay from 10s to 5s

Small changes: remove blog, add az block groups, lower warning message show time

---

main/static/main/css/style.css
main/static/main/js/geo.js
main/templates/main/entry.html
main/templates/main/entry_map.html

Reverts Representable/representable#642

Revert "restore bugfixes: enter when mapping, selecting units on mapping page"

---

main/static/main/css/style.css
main/static/main/js/review.js
main/templates/main/review.html

**changes**
- On the "My communities" page, adds checkmark that gives users the ability to select particular communities to view
**to test**
- Go to the "my communities" page on an account with communities
- Verify that no communities are displayed
- Verify that upon hovering over a hidden community, it appears highlighted on the map then disappears when you stop hovering
- Verify that clicking the check box displays the community, and removing the check hides it

Select Communities to View in "My Communities"

---

main/static/main/css/style.css
main/static/main/js/review.js
main/templates/main/review.html

Reverts Representable/representable#622

Revert "Select Communities to View in "My Communities""

---

main/views/dashboard.py
main/views/main.py

Communities not hidden (ie admin approved) when retroactively added .

comms not hidden

---

main/static/main/js/map.js
main/static/main/js/submission.js

on submission page:
https://user-images.githubusercontent.com/68291744/111668017-aaf24300-87eb-11eb-9bab-cedcd3ef634f.mov
on state map page:
https://user-images.githubusercontent.com/68291744/111668024-ae85ca00-87eb-11eb-9af4-bdbc909ce1d1.mov

only allow one layer to be checked at a time

---

.pre-commit-config.yaml
main/static/main/js/components/keys.js
main/static/main/js/map.js
main/static/main/js/submission.js
main/templates/main/submission.html
main/views/main.py

I turned off the prettier hook so I think that got rid of most of the problem of excess changes. I think the black hook might have still made 2 modifications to main.py but that's it. Other than that I think everything still works like it did before.

Redid changes in clean branch

---

main/static/main/js/map.js
main/templates/main/map.html
main/views/main.py

**changes**
- Changes export buttons to export all the selected cois on the state map page. If no cois are selected it exports all of the cois.
**to test**
- Go to state map page.
- Try selecting specific cois then exporting them to geojson and csv. Confirm that only the cois you selected were exported
- Uncheck all the selected cois or press "Show All" then export the cois. Confirm that all the cois were exported.

Export Selected Cois on State Map Page

---

main/static/main/css/style.css
main/static/main/js/components/dropdown.js
main/static/main/js/geo.js
main/templates/main/base_nofooter.html
main/templates/main/entry.html
main/templates/main/entry_map.html
main/templates/main/entry_survey.html
main/templates/main/index.html
main/templates/main/pages/faq.html
main/templates/main/state.html
representable/templates/base_nofooter.html

**changes**
- Changes question button on map page from producing a dropdown to producing a modal
- Removes pictures on survey start page
- removes the footer from the survey entry flow
- fixes dropdowns on the state pages

Frontend Fixes

---

main/templates/main/drives/page.html
main/templates/main/state.html
main/templates/main/state_info.html

**changes**
- updates drive page to include updated format of state page
- removes drive description if it equals None
**to test**
- create a mapping drive with no description
- go to drive link
- check state info looks as expected and no drive description appears

drive page updates

---

main/templates/main/map.html

Map page fix

---

main/templates/main/dashboard/partners/thanks.html

* Fix server 500 when creating org

server500 when making org

---

docs/docs/setup2.md
main/templates/main/drives/dane-county-page.html

- Dane county typo fix
- doc update: add email forwarding

Staging release 6/1/21

---

docs/docs/setup2.md
main/templates/main/drives/dane-county-page.html

- Dane county typo fix
- Docs update: email forwarding

Production release 6/1/21

---

main/templates/main/entry_map.html
main/views/partners.py

**changes**
- fixes bug where searching geocoder on map page too quickly opens help modal
- fixes bug where communities being reported by an org admin are not auto unapproved
**to test**
- check mapping page geocoder bug doesn't exist
- check that reporting a community as an org admin works as expected

Bugfixes june 11

---

main/static/main/css/style.css
main/static/main/js/geo.js
main/templates/main/entry_map.html
main/templates/main/entry_survey.html
main/templates/main/index.html
main/templates/main/state_info.html

**changes**
- lots of small changes (typos, formatting, etc)
- update help button and comm info buttons on map page
- update appearance of map tools buttons on map page
**translations note**
- won't require any changes to translations, but will require a re-compiling of the django.po file, I believe, since there's a couple typos / spaces that have been changed @Chuk116 @jasony123123 
help modal on map page: 
comm info section with updatd width:
updated buttons appearance:

Polish session 6.24 changes

---

main/admin.py
main/models.py
main/views/main.py

testing should be pretty simple, though not sure when you can do it given problems in main. functionality should be identical to previous version, so we basically just need to test that it works the same as before. to test:
- submit profane entries (in any of the fields) and make sure that a report gets filed
- submit non-profane entries (in any of the fields) and make sure that a report doesn't get filed
- also make sure that there are no errors upon submission

fewer API calls / simpler code

---

main/static/main/css/style.css
main/templates/main/index.html
main/templates/main/pages/resources.html

**changes**
- changed "PARTNER WITH US" on home page to say "JOIN AS AN ORGANIZATION"
- updated user demo video link to reflect updated video (thanks Mikala!)
- updated sizing of transparent blue box on home page to not go off page
- removed repetition of steps on home page
**to test**
- check that all the above changes ^ behave as expected
**screenshot**

various cosmetic / polish changes

---

main/static/main/js/submission.js
main/templates/main/entry_address.html

- added arrow to why do we need your info
- made state portal link open in a new tab

couple minor style things

---

representable/custom_storage.py
representable/settings/base.py
requirements.txt

aws buckets for logo pics
to test:
- pip install -r requirements.txt
- make an org with a pic
- make a drive
- see if that drive shows the picture that's uploaded

aws s3 bucket for media

---

main/static/main/js/components/dropdown.js
main/static/main/js/geo.js
main/static/main/js/map-common.js
main/templates/main/entry_preview.html
main/templates/main/entry_survey.html
main/templates/main/state_info.html
main/templates/main/submission-copy.html
main/templates/main/submission.html

I added a bunch of tracking stuff. I'm not sure how to test other than just to go through making a community and make sure stuff isn't messed up? I don't think this would impact anything visibly and I can't test properly until it's on staging unfortunately.

Mixpanel added tracking

---

main/static/main/js/map.js
main/static/main/js/submission.js

**changes**
- fixes a bug (sorta) where COIs with multiple loops
**to test**
- draw a COI with multiple pieces (easiest way to find this is to poke around the Dane County wards -- http://127.0.0.1:8000/drive/tell-us-about-your/ )
- check that two pieces of the COI are visible on the submission page
- check state and drive map pages for accurate visualizations

Visualize multipolygons (2 rings)

---

main/static/main/js/map.js
main/static/main/js/submission.js

due to difficulties with the implementation of the google authentication PR on staging, creating this PR to push time-sensitive changes to production
- visualizes multipolygons up to two rings
- changes map pages colorway
- fixes bug with zoom for state map pages

Dane wi fix prod push

---

main/static/main/js/components/keys.js
main/static/main/js/geo.js

Handles new census data files
- changes feature referenced for block/bg id
- allows population display on any state with new data
test
- go to new mexico and map with both blocks and block groups, try switching, etc
- make sure it submits and everything, and population works as expected
okay SO i made mbtiles for all the states, but only uploaded nm so far for testing because there's no one there so hopefully it won't mess anything up, anyway the issue is that the files actually have weird geoids now so if i uploaded them and didn't change prod it would break (like the ok/il thing). So either they have to be uploaded concurrently with changes to prod, or i have to except for the length of the geoid every time it's referenced, which i started doing but was afraid it would be buggy and …

New census files

---

main/static/main/js/geo.js
main/templates/main/entry_map.html

**adds municipal wards wording to replace "census block groups" on faq, only for Dane Cty drive**

add municipal wards wording to faq

---

main/static/main/js/components/keys.js
main/static/main/js/map-common.js
main/static/main/js/map.js
main/static/main/js/submission.js

go to keys.js and add to last lists the layers we want
https://docs.google.com/document/d/1UCaIjenkK3XKb2AiSKwhmxniUUgFhZrgN5J8qexTLUQ/edit
here's the keys ^
other than that layers should come up on submission page and comm map page

final dem layer feature, needs layers added in keys.js

---

main/static/main/js/map-common.js
main/static/main/js/map.js
main/templates/main/map.html
main/templates/main/partners/map.html
main/templates/main/submission.html

layers clearer
