Representable/representable

- main/forms.py
- main/models.py
- main/templates/main/dashboard/partners/thanks.html
- main/views/dashboard.py
- main/views/main.py
Whitelist fixes:
- When user uploads submission with an org selected, checks if they are a member of that org. If so, sets the admin_approved field of the entry to true. 
- If they are not a member, checks if they are on the whitelist. If so, adds them as a member and deletes whitelist entry.
Org member form fixes:
- Stops creating duplicate members when on the member creation form (local link to creation form: http://127.0.0.1:8000/dashboard/partners/[org_slug-id]/members/create)
Resolves #41
> Working whitelist, improved member form 

- main/static/main/js/geo.js
- main/static/main/js/map.js
- main/static/main/js/partner_map.js
- main/templates/main/pages/entry.html
- main/templates/main/partners/map.html
- main/views/partners.py
- updated wording on entry page (not just zipcode)
- made default map of the entire US (entry page and partner map page)
- changed census block shading to be gray + more transparent, generally (TODO: update to a log scale, maybe?)
- updated partner map page to display org name, in place of spacebar
- partner maps zoom to where communities have been drawn (if no approved communities, remains on map of whole us)
- updated community visualizations to be more distinguishable
- updated census blocks to be less obstructive
- census block and legislature layers now have a minzoom, so they don't clutter the map when zooming out (also reduces lag) (TODO: explain this in tooltip)
> a collection of small changes to visuals

- main/static/main/js/geo.js
Bug mentioned by Sandy - community too big to draw - because we were using the area for NJ.
Expanded this check for all 50 states.
Notice the print statement to the right that pushes the error for the michigan coi and deletes a vertex to take care of it.
> bug for polygon too big for michigan - updated area for all states

- main/static/main/js/geo.js
Resolves #44 
**To replicate:**
1. Go to last section of the entry. 
2. Search for 08544.
3. Max zoom level is set to 17 now, so people can see small roads if they choose to, but not close enough so it's confusing/ugly.
> Fixing Max Zoom Level on Entry Page

- main/forms.py
- main/static/main/js/geo.js
- main/templates/main/pages/entry.html
- Removed Next/Previous Buttons.
- Removed Edit Section/Hide Section buttons.
- Expanded all sections by default.
- Consolidated Interests into one section.
- Added community name after issues field.
To test:
- Open entry page and fill form.
- Pay attention to examples and questions. Please raise any issues that may arise with
> Form Consolidation (Combining interests/Expanding Sections/Removing Buttons)

- README.md
- main/static/main/css/style.css
- main/static/main/js/geo.js
- main/templates/main/pages/entry.html
Closes  #86. Closes #61.
- Adds "Edit Polygon" button that puts the map in "direct_select" mode where the users can select vertices to remove them or add new ones.
- Adds "Finish Drawing" button that makes it easier for new users to finish drawing a polygon (they don't have to figure out that you need to connect the final vertices or press the "Enter" key).
- Adds "Clear Polygon" button that removes anything that's on the map.
- Adds "Delete Vertex" button that removes one vertex at a time (repurposed Mapbox delete button).
- Adds information box that helps users understand how to edit the drawn polygon.
- Adds the Representable.org colors to the Readme for easy reference.
- Temporary (before we update the form altogether): Expands all sections by default.
**What to look for:**
- Go to …
> Streamlined Map Editing Buttons

- main/static/main/css/style.css
- main/templates/main/campaigns/page.html
- main/templates/main/pages/michigan.html
Key changes:
- Adds Michigan content from @psiyer7 
- Simplifies Michigan page html and makes it mobile-friendly
- Changes row-content definition globally (resolves #127 )
Steps to replicate/test locally:
- visit `localhost/michigan` and see content changes
- create a campaign with the state set to MI
-  see the "general information about redistricting in MI" on the campaign state page
Todo: 
- Simplify campaign dashboard
- Consider further state page changes, adding dynamically updated campaigns and orgs (out of scope for M2 rollout)
Screenshots:
> Michigan content updates

- main/static/main/css/style.css
- main/static/main/js/geo.js
- main/templates/main/pages/entry.html
Closes #103. Closes #111. Closes #105.
A few form validation changes:
- If the user enters a polygon correctly but makes a mistake in another field the map will redraw the polygon, highlight the right blocks, and zoom into the right state. Uses sessionStorage to remember the state found by the user via the geocoder.
- Added form entry errors on all fields using alerts.
- Added red borders to fields in order highlight fields missed by the user.
- FIXES error on pressing "Draw" again. In the past, if user pressed draw, the polygon would disappear but that wouldn't update the entry. Thus, it was possible for the user to submit the wrong polygon if they didn't pay attention.
How to test:
- Try to leave a field non filled. The border should turn red.
- Draw a polygon but DONT fill any of the …
> Form Validation Updates

- main/templates/main/pages/michigan.html
From @psiyer7: two grammatical errors on the user testing campaign page for VNP. We should change "It's important the these" to "It's important that these"
Also "the Michigan's Redistricting" should be changed to "the Michigan Redistricting"
Changes made as described above (content only).
> Fix Michigan content typo

- main/templates/main/partners/get_started.html
Key changes:
- Changes the partner welcome page "create organization" button to "request early access" which pops up with an email to team@representable.org. This will hopefully help avoid people creating an org without our knowledge or help (for now). Note: this does not disable creating an organization (which we'll need to think about doing in future):
Screenshots:
> Change create organization link to request early access

- main/admin.py
- representable/settings/base.py
- requirements.txt
Opening this issue to resolve #213 : we need a way to share the results of this round of testing with partners. The easiest way to do this seems to be from Django admin so that's what I decided to try.
Key Changes:
- Registers CommunityEntry model in Django Admin
- Sets up django import export to export communities
- Optionally filter communities by organization
To test:
- Create a super user (or log in with one)
- Login to django admin at localhost_url/admin
- Click on community entrys (should be spelled entries - but the plural was set automatically)
- try filtering by community and org
- see that export works for xlsx (excel), and json
Notes:
- CSV export not working properly because polygons are not easily serialized in CSVs. I think this is fine because we can export properly in …
> Add multi-entry export functionality in Django Admin

- main/forms.py
- main/templates/main/entry.html
Edits to make the community interest boxes less intimidating / more user friendly.
1) Shrunk box size from 5 lines to 3 lines
2) Slight edit to economic interest prompt such that all question prompts are now 1 or 2 lines.
To Replicate:
python manage.py runserver
Visit entry page
> Entry form edits; smaller form size

- main/static/main/css/style.css
- main/templates/main/state.html
**changes**
- responsiveness of state svg (wrapped in card)
- removed exclamation point
- jumbotron w/ rounded edges for COI section
- join drive button larger + primary coloring
- reduced drop shadow of cards
**to test**
1. go to state page
2. play w responsiveness
**of note**
- please comment any additional thoughts on formatting -- this is all easy stuff to change (for the most part)
- in the future, i think it would be great to have some themed drawings of some sort, like we have on the landing page
- maybe we want to de-emphasize the final "draw my community" button by making it an outline
**screenshot**
> state template formatting updates

- main/templates/main/partners/get_started.html
- main/views/dashboard.py
Key Changes:
- Simplified org creation flow by remove request access. Now it's get started (takes you to org creation form) and request demo (for those who aren't sure yet). 
- Automatically emails team@representable.org when a user has created an org. 
- Includes user details in email (see screenshots) for easy follow up
- Updated info on partner page to reflect community mapping drives
To test:
- I tested this by checking the email in the console after creating an org at: http://127.0.0.1:8000/dashboard/partners/create/ 
- I also tried moving email settings from prod.py to base.py to make sure the email would actually send and it did for me.
- Play around with button behavior, review content at: http://127.0.0.1:8000/partners/welcome/
Screenshots:
> Add info to partner page, auto email when org is created

- main/static/main/js/components/keys.js
- main/static/main/js/map.js
- main/templates/main/partners/map.html
- main/views/partners.py
closes #265 
** changes **
- added ward + community area files to mapbox tilesets
- display Chicago ward + community outlines on map views for illinois only
- map views only show state specific layers for org/drive views now (instead of all)
** to test **
- create an illinois organization/drive
- go to map page
- under "data layers" select "chicago wards" or "chicago community areas"
** screenshots**
> chicago ward + community area data

- main/fixtures/single_org.json
- main/templates/main/dashboard/drives/create.html
- main/templates/main/dashboard/partners/thanks.html
- main/views/dashboard.py
**Changes**:
1) When an organization is created with a not verified account: Resends verification email link, displays modified message  "please verify account, email verification is necessary for certain features ..."
2) When a not verified account attempts to create a community drive: Does not let the account create a drive, displays message "email verification is necessary to access this feature ...", Resends a verification link.
**To test**
Make an organization with a not verified email account.
Check to see verification link is resent.
Check to see that a modified message is displayed.
Try creating a community drive with a not verified email account
Check to see verification link is resent.
Check to see that the following modified page is displayed instead of the Create a Drive form. …
> Email Verification in Organization Flow

- main/templates/main/dashboard/drives/index.html
- main/templates/main/drives/page.html
- main/templates/main/entry.html
- main/templates/main/state.html
- main/urls.py
- main/views/main.py
**Overview**
Setup for entry state view without any changes to geo.js. Changes to displaying the map in geo.js will be added soon in a seperate PR from a branch up upto date with the select tool.
**Changes**
Pages associated with a state now can store that information in the URL; example /entry/MI/
State pages, campaign pages, and campaign links, now link to a page with the state information.
**To Test**
Navigate through these different ways of accessing an entry page associated with a state:
1) From home page, select a state with a state page (ie. Michigan). Then click "Draw my Community. 
2) On the state page, also try clicking "Join Drive"
3) Navigate to your dashboard, create a drive, go to the entry page from that new drive.
Then check the url, to make sure that the state …
> Entry State Views Setup

- main/static/main/js/geo.js
Resolves #291 
This is a simple solution to the problem of accidentally deleting a community. I feel like it could be prettier (this could be a future PR?) but it's reliable and prevents the frustration of accidentally clearing a community
Key Changes:
- Add confirm dialog that asks user to confirm they to clear map before proceeding
To test:
- Go to entry page
- try pressing clear polygon after selecting a few blocks
Screenshots:
> Add confirm dialog to confirm the user wants to clear map before proceeding

- main/static/main/js/geo.js
**Changes**
For entry pages associated with a drive, or associated with a state - have the map immediately display zoomed into the center of that state. 
Also fixed small bugs and wordings in step by step guide (ie. removed "radius bar" terminology)
**To Replicate**
1) From entry page, click on a state that has a state page (ie. Michigan). Click "draw my community" or join one of the drives. Alternatively, make your own org and drive, and navigate to the associated entry page.
2) Check that the map on the entry page is displayed initially zoomed to the associated state.
3) Check that census blocks are initially displayed for the associated state.
4) Play around with select tool to make sure things work as usual. Also click step by step guide and check that the terminology and steps make …
> Initial Map for Entry_State_View

- main/static/main/js/components/keys.js
- main/static/main/js/map.js
- main/static/main/js/submission.js
**changes**
- switching from custom uploaded tilesets for blocks and legislature
- adding new data layers: neighborhoods, 5-digit postcode areas, congressional districts
- simplify code on map.js
**to test**
- go to any map page
- select and deselect data layers. ensure no js errors
**next steps**
- implement boundaries in geo.js (need to spec out)
- data joins to enable ids & labels for data layers
- hover for label
- custom tilesets still needed for school districts
- vary colors of data layers
> implement mapbox boundaries on map page

- main/static/main/js/geo.js
- main/static/main/js/submission.js
- main/templates/main/entry.html
- main/templates/main/submission.html
**changes**
- added an undo button on the entry page with the following behavior
- after an action which draws, erases, or clears the map, allow to undo the previous action
- if there is no action to undo, raise a warning
- undo only applies for actions which impact the drawn community (ex. using the eraser but not deselecting any area doesn't apply)
- trying to clear an empty map raises a warning
- updates selection area upon using eraser tool or undo tool to fix edge cases for contiguity test + submission
- fix bugs on submission page
**to test**
- search to begin drawing community
- try clearing an empty map. test that it raises a warning
- try undo-ing a non-action. test that it raises a warning
- test out drawing and subsequently undoing actions
- submit & confirm …
> entry page undo button

- main/templates/main/dashboard/drives/index.html
- main/templates/main/dashboard/partners/index.html
**Change:**
- buttons (on list items that include links) on org and drive home pages to be responsive
**To test:**
- navigate through the org dashboard on a mobile/developer tool that shows the mobile site
- navigate through the org dashboard on resized browser
Closes #157
> Org dash responsiveness

- main/templates/main/dashboard/drives/index.html
Resolves #365 
Key changes: 
- Fixes a bug where state code was appended to drive url in the dashboard
To test:
- Visit link on dashboard
> Fix link to drive on organization dashboard

- main/static/main/js/mixpanel.js
Resolves #298 
Key Changes:
- Simplifies logic so that only opt in or opt out is displayed, not both
To Test:
- try toggling settings on dashboard
> Fix bug that shows duplicate tracking settings

- main/static/main/js/geo.js
- main/templates/main/drives/page.html
- main/templates/main/entry.html
- main/templates/main/state.html
- main/views/main.py
**changes**
- display map on /entry/{state_abbreviation} for all states when clicked on the map
**to test**
- go to map on landing page
- select a state without a state page, check map shows on entry page
- select a state with an entry page, check map shows
- go to a drive link :: /drive/{slug}, click on "Draw my community", check map shows
**other considerations**
- now, the only way to get to /entry/ is through the "Add community" button in the header -- we may want to redirect this button to go to the state selection screen on the landing page
> state entry pages for all states

- main/views/main.py
Key Changes:
- Adds a 404 redirect for empty submission link without map_id param 
- Adds 404 redirect for invalid submission links (do not match re expression)
- Also redirects to 404 if map_id is queried and no submissions are found
- Resolves: https://github.com/Representable/securetracker/issues/7
Additional Context:
- Django sanitizes queries and protects from SQL injection attacks. However, re match and 404 fallbacks makes this failproof!
To test:
- Visit a map/drive, ensure that clicking on a community take you to a valid submission link
- Create a community then visit the link to the community on the thanks page
> Add checks, 404 redirect for invalid map_id param on submission urls

- main/templates/main/state.html
Key Changes:
Temporary redesign of state page while we reconsider flow, removes community drive links
To test:
Visit any state page
python create_state_fixtures.py on local or visit admin -> states -> editor for state of choice
Screenshot:
> Remove drive section on state page

- main/templates/main/pages/about.html
adding the names of the founders and a short blurb about how Rep started to the about page
> add founding team section to about page

- representable/templates/base.html
- creates a navigation dropdown if the user is admin of 3+ organizations (avoids clutter at top of screen)
- closes #427
> create nav dropdown when admin of 3+ orgs

- main/forms.py
**changes**
- frontend form textareas now only allow input up to the maximum length in the model
**to test**
- try and write something over 500 characters for entry reasons areas
- try the same but 100 char for other areas etc
> Add form length limits to frontend

- main/forms.py
- main/static/main/js/dash_review.js
- main/static/main/js/geo.js
- main/static/main/js/map.js
- main/static/main/js/review.js
- main/static/main/js/submission.js
- main/templates/account/login.html
- main/urls.py
- main/views/dashboard.py
- main/views/main.py
- representable/templates/base.html
**changes**
- Display red bootstrap alert when a user enters a mismatched password
- Removes the zoom buttons on all of the maps when the device width is 760px or less
- Changes the state selection dropdown on the drive collection page, to only show the states that the organization is in.
**Issues Addressed**
- https://github.com/Representable/representable/issues/448#issue-726603352
- https://github.com/Representable/representable/issues/433#issue-718249746
- https://github.com/Representable/representable/issues/428#issue-718241574
**To test**
- On the login page type in a username and password that is incorrect. Should see red alert above the text boxes
- Go to a mobile phone device (< 760px) on the developer tool or use a mobile phone. Go to a map that originally had the zoom buttons. …
> Login, Zoom Buttons, and Drive Creation issues fixes

- main/models.py
added blank=True and null=True to drives require_user_addresses field - to fix bug with clicking on an org
> require_user_addresses bug fix

- main/forms.py
- main/static/main/css/style.css
- main/static/main/js/auth.js
- main/templates/account/login.html
- main/templates/account/signup.html
- main/templates/account/signup_login.html
- main/urls.py
- main/views/main.py
- representable/settings/base.py
**changes**
-Authentication page now features the login form and signup form side by side with a new appearance
-Authentication redirection now features an alert at the top telling the user that login or signup is required.
-Authentication errors results in a red banner at the top of the form where the error occurs
-Username is now removed from the authentication process entirely: Closes #441 
**to test**
-Click login or signup button. If you click the login button, the focus should be on the email textbox of the login form. If you click the signup form should be on the email textbox of the signup form.
-On small tablet and mobile view, if you click on the "signup" and "login" links at the bottom of each form, the screen should be scrolled to and the focus should be on that respective …
> Login redesign fixed

- main/static/main/css/style.css
- main/templates/main/entry.html
**changes**
- Changes the position of the recaptcha box to be centered within the privacy card
**to test**
- Go to the entry form page of any state and scroll to the privacy section
*Note: The red text should not be present on production*
> Changes the frontend design of the racaptcha box

- main/static/main/css/style.css
- main/static/main/js/geo.js
- main/templates/main/entry.html
- main/templates/main/index.html
**changes**
- changed initial mapping form to a basic mode wherein users can select + deselect individual census block groups, one at a time. Click to select. Click to deselect.
- added a dropdown settings button, which when pressed allows users to interact with the same mapping controls as before (selection size, eraser, etc)
- when closing the dropdown, keeps the same selection size/eraser/draw options, with the exception of the case where the selection size is 0, or minimum
**to test**
- mess around with drawing a community
- check contiguity test (can you draw communities of geographically discrete block groups?)
- check that mapping behaves as expected when switching between the settings dropdown
**note**
- plan is to merge this into staging so that both sites can …
> Simplified mapping controls

- main/static/main/js/submission.js
word wraps long text (URL) that appear when exporting PDF...
To test:
1. Get a community and export PDF
2. The URL should never run off the page no matter how long it is
Resolves #483
> pdf word wraps long text

- main/views/main.py
Users can't access entry/* where * is a keyword that is not a state abbreviation
To test:
Go to entry/* where * is not a state abbrev and check if you are redirected to the state selection page
> state name entry page bug fix

- main/models.py
- main/views/main.py
- main/views/partners.py
- requirements.txt
Changes made:
* revert getting entries from aws for partner map/drive map/submission and review pages
* restored original geojson export functionality for submission/review/map pages
To test:
* create an entry in a drive
* view the map page for the drive
* view the partner map page for the org
* go to the review page and find ur entry
* export entries on the review page
* go to the submission page for the entry
* export the entry on the submission page
* go to the drive page and export entries
* go to org map page and export entries
> Revert get calls to AWS

- main/forms.py
- main/views/dashboard.py
When creating a new org, only a single state can be selected. Once an org is created, the state cannot be changed anymore.
Does not change the Organization Model to force only 1 state ... since old organizations might have multiple states already attached.
To test: try creating an organization and editing an organization
> frontend forms only accept 1 state

- main/static/main/js/geo.js
To test:
Go to survey page
At the map drawing step, note when you search something on the modal, the modal automatically disappears
> modal shud vanish when geocoder searched

- main/static/main/css/style.css
- main/templates/main/entry.html
- main/templates/main/entry_survey.html
**changes**
- Increases the text size of the text on the survey start page
- Fixes the COI definition dropdown issue that occurs on safari Issue #581 
- Fixes the formating and sizing for the numbered circles on the survey start page
> Text Size Increase, Safari COI Dropdown Fix, Survey Start Numbered Circles Fix

- main/static/main/css/style.css
- main/static/main/js/geo.js
- main/templates/main/dashboard/partners/review.html
- main/templates/main/entry_map.html
- main/templates/main/map.html
- main/templates/main/partners/map.html
- main/templates/main/review.html
- main/templates/main/submission-copy.html
- main/templates/main/submission.html
**changes**
- when erasing on the map, checks for contiguity
- if erase would lead to a non-contiguous selection, displays an error message and doesn't allow the user to erase
**to test**
- go to mapping page
- create a contiguous selection
- try to erase a block in the middle that would lead to a non-contiguous community
- check error message appears and you aren't allowed to erase
**note**
- as with the contiguity feature from before, there are occasional edge cases where you can end up with a non contiguous community. this is due to the irregular nature of census block groups
> Map contiguity check for erase

- main/static/main/css/style.css
- main/static/main/js/geo.js
- main/static/main/js/submission.js
- main/templates/main/entry_survey.html
**changes**
- clicking on a text box automatically opens up the examples, if not already visible
- text box remains blue when typing
- blocks using the back button after submitting a community
**to test**
- add your community
- on survey page, check for expected behavior
- after submitting community, check that back button is blocked
> Entry page small changes + bugfixes

- main/static/main/js/components/keys.js
- main/static/main/js/map.js
**changes**
- increased the thickness of data layers on visualization pages
- removed COI outlines
- edited hover impact on COI view to be more emphatic
- added different colors for data layers (question: do we want to limit people to only having one data layer visible at a time?
- 
**to test**
- go to map page (preferably one with many overlapping COIs)
- check data layers, aesthetics, no errors, etc
two overlapping communities with no borders:
hovering over one of the two:
congressional districts:
state house districts:
(not going to upload a pic of each layer but you get the point. each one is a different color)
> visualizations: line thickness, colors, COI outlines

- main/static/main/css/style.css
- main/static/main/js/geo.js
- main/templates/main/entry.html
- main/templates/main/entry_map.html
- main/templates/main/entry_survey.html
**changes**
- fixed bug where if you pressed enter when searching for a place to start on map page, it would result in you seeing both the address portion of the survey page as well as the privacy portion at the same page (problem: buttons needed to have type="button" so they wouldn't be form focused, and added a dummy button with type="submit" in form so that pressing enter doesn't trigger form validation
- fixed bug where users couldn't select units on the same line as the "back" and "next" buttons on map page
**to test**
- go thru survey user flow
- on map page, search for a zip code then press enter key
- select units on map page that were on the same line as the next button
- click next
- check no errors
> two entry page bugfixes

- main/static/main/js/components/keys.js
**changes**
- switches Michigan, New Mexico, North Carolina, Pennsylvania, Nevada, Utah, and Washington to 2020 Census block groups, as per partner feedback
**to test**
- try drawing a COI in any of these states
- check no errors
> 2020 blockgroups : mi, nm, nv, nc, pa, ut, wa

- main/static/main/js/geo.js
- main/templates/main/entry_map.html
- main/templates/main/entry_privacy.html
- main/templates/main/entry_survey.html
**changes**
- fixed bug where it's not possible to erase the first block group you select
- restored contiguity check so it doesn't give warnings as much
- fixed (mostly, it's kinda finnicky because of the way mapbox does things lol) the bug where a COI could be drawn and would then be cut off -- added a delay when pressing "save" on the mapping page that pops up the "saving community..." box
- fixed missing circles on entry preview page
**to test**
- python manage.py runserver 
- draw a COI - check that you can erase the first block group you select
- select an area, drag map away from said area so that the COI is not visible, then check that COI saves appropriately
circles
> various bugfixes + contiguity check improvement

- main/static/main/css/style.css
- main/static/main/js/geo.js
- main/templates/main/entry.html
- main/templates/main/entry_map.html
**changes**
- restored bugfixes that got overwritten: pressing enter on modal on mapping page no longer results in multiple steps showing at once, can now select units in the same line as the back and save buttons when mapping
> restore bugfixes: enter when mapping, selecting units on mapping page

- main/forms.py
- main/templates/main/dashboard/partners/index.html
- main/templates/main/dashboard/partners/member_form.html
- main/views/dashboard.py
**Changes**:
* removed the dropdown
* need to provide full email of admin
* shows error and reloads form if incorrect email or user does not exist
* redirects otherwise
**To test**:
* python manage.py runserver
* go to your org
* manage the org admins
* add more admins
* add the admin email
* check the admin page to see if they were added
* put in incorrect email and check if the error was displayed
> need to provide admin email to add administrators to org

- main/admin.py
**changes**
- adds organizations to django admin, from which anyone with admin access can add verification
**to test**
- go to http://127.0.0.1:8000/admin/
- go to Organizations
- change an org to Verified = true by checking the checkbox
- check that org appears verified on site!
> Add Organizations to Django Admin (for verification)

- main/templates/main/submission.html
fixes bug where an authenticated user can add another user's community to a drive
**to test**
- create a community
- copy url to submission page
- log out and log into different account
- go to submission page url
- check that no "add this community to an organization" card appears
> bugfix: ability to add to drive if not community author

- main/views/main.py
- main/views/partners.py
**changes**
- adds 404s when get() django functions return DoesNotExist: state map pages, org map pages, and drive map pages
**to test**
- test on nonexistent state: http://127.0.0.1:8000/map/xx/
- test on nonexistent org: http://127.0.0.1:8000/map/p/fake-org-link/
- test on nonexistent drive (with real org)
> add 404s for map pages

- main/static/main/js/submission.js
**changes**
- altered zoom to community on submission page to better fit the community on smaller resolution screens
- sanitized community information text to only include ASCII characters
- makes zoom instant for export to avoid strange pdfs if export button is immediately pressed before mapbox has time to zoom
**to test**
- create a community, include non ASCII characters in description
- export pdf on submission page (important: use a smaller resolution so that the map appears to have roughly a 2:1 aspect ratio
- check no errors
the map
pdf
> PDF export fixes

- main/admin.py
**changes**
- adds drives section of django admin
- adds testimony length to django admin
**to test**
- navigate to : http://127.0.0.1:8000/admin/
- check drive and communityentry models for errors
> add more metrics/functionality to django admin

- main/views/main.py
**changes**
- added 404 for links to drives on entry page that don't exist
- added redirect when url is changes on entry page that includes a state
**to test**
- go to entry page drive link
- edit drive slug to be something fake (ex: illinois-drive -> illinois-drive-fake)
- check 404 appears
- go back to correct drive link
- change state abbreviation
- check redirect occurs
> add exceptions for drive url errors

- main/static/main/js/geo.js
**changes**
- makes it so that users cannot go to next step of survey flow if they leave all entries blank
- works for custom questions too
**to test**
- create a community, with no answers for survey questions
- check validation fails on frontend, stops user from advancing
> fix frontend validation for survey questions

- main/static/main/js/components/states.js
- main/static/main/js/submission.js
- main/templates/main/dashboard/drives/create.html
- main/templates/main/submission.html
**changes**
- added copy link on submission page, for folks who want to share their community via the custom link of their submission
- added the WA public input portal link to submission page for COIs drawn in the state
- update wording when creating a drive for clarity on custom drive questions
**to test**
- draw a community in WA
- check public input portal link appears on submission page
- check that "copy link" button underneath export buttons works as expected
**translations note**
- this adds two things for translation: the line on the submission page about copying a link, and the line on the drive creation page which now includes an extra sentence
copy link (text changes to say "Copied!" for 1.5s after clicking
> copy page link on submission + other various features

- main/templates/main/map.html
- main/templates/main/partners/map.html
- main/views/main.py
- main/views/partners.py
**changes**
- adds a date display on state map pages in the format like "Dec. 18, 2020"
- orders communities by date on all map pages -- most recently drawn communities show at the top of the list
**to test**
- go to state map page with multiple communities drawn
- check that date appears within "more info" dropdown
- check that dates are in order of most recent first
- check the same for a drive and organization map page
> displays and orders communities by date

- main/static/main/js/geo.js
- main/templates/main/entry_map.html
**changes**
- updates modal when entering entry map page to include units as "municipal wards" rather than "census block groups"
**note**
- changes translations needs
> census blocks -> municipal wards in mapping modal

- main/models.py
- main/static/main/js/geo.js
- main/static/main/readme/README_csv.txt
- main/static/main/readme/README_geojson.txt
- main/templates/main/map.html
- main/templates/main/partners/map.html
- main/templates/main/submission.html
- main/templatetags/representable_extras.py
- main/views/main.py
- main/views/partners.py
**changes**
- switches export of individual communities to a zip file with the original file type (geojson or csv) and a readme (due to a bug it isn't possible at the moment to do the same for the multiexport -- working on that)
- updated storing of census block and block group manytomany field when saving a community to work properly
- updates csv file to match block equivalency format : includes BLOCKID (census FIPS code) and DISTRICT (0 for single community, counts up for multiple)
- changes the name of exported files to match more closely with the context of what's being exported: the name of the community for single export, and the name of the state/drive/org for multi export
- update municipal wards redistricting export in wisconsin to export census block ids rather than municipal …
> changes to export functionality

- main/templates/main/submission.html
**changes**
- adds question mark next to "Community Information" for more context
- button triggers a modal that repeats the survey questions + includes the response of the community, if there is one
- adds a few lines that will need to be translated, but the questions and the examples remain translated as they do on the survey page
> Add survey questions as context to submission page

- main/admin.py
**changes**
- adds more information to organization tab on django admin
- adds dates of community entries to filter by (ex: how many communities were drawn in june 2021)
- allows filtering by state for each entry
- adds more information to drive tab on django admin
- adds ability to export a csv of organizations and drives
- adds ability to export a csv of user email addresses (can filter by org/drive first)
- adds tags and filtering by tags to community entry in django admin
**to test**
- navigate to http://127.0.0.1:8000/admin/
- check organization, communityentry, and drive views
- check all expected values are there as expected
- check all filtering works as expected with no errors
- check that all exporting works as expected with no errors
> django admin update

- main/static/main/js/map.js
- main/templates/main/map.html
- main/templates/main/partners/map.html
- main/views/main.py
- main/views/partners.py
**changes**
- updates visualizations so that place names appear above cois
- for map pages with 25+ cois, adds a variable opacity system, depending on the number of blocks or block groups that comprise a community
before:
after:
> variable opacity on map pages

- main/views/main.py
**changes**
- adds testimony zip file to single coi csv export
- adds testimony columns to multi-coi csv export
**to test**
- go to submission page, click to download as csv
- check that zip contains a testimony csv file with the correct information
- go to state or drive map page
- check that csv download contains columns for testimony attributes, and name + address if you are admin
> adds more testimony to csv files

- main/admin.py
- main/templates/main/partners/map.html
- main/views/main.py
- main/views/partners.py
**changes**
- removes showing and querying addresses for drive and org map pages
- adds entry_ID to export functions, so that entries can be consistently matched with testimony
**to test**
- go to drive map page
- check no errors, addresses don't show up
- export as geojson
- check that entry_ID is included
- go to django admin
- export community testimony
- check that entry_ID is included, and so is address
> remove address from map pages, add entry id to export

- main/static/main/js/geo.js
from 800 to 4000 block groups, and from 2400 to 10000 blocks
as per NJ partner request
> increases size limit of cois
